### ISSUE TITLE
Public Key format in v1.3 is different than v1.0

### ISSUE THREAD

**Issue by b00f** [maxonrow/maxonrow-go#103]
The format of public key is different that previous version:
old format:
<img width="1270" alt="Screenshot 2020-04-17 at 2 44 13 PM" src="https://user-images.githubusercontent.com/8073510/79713972-fa8d6d80-8301-11ea-89ed-88592bf7e3b2.png">
vs new format:
<img width="1410" alt="Screenshot 2020-04-17 at 2 43 33 PM" src="https://user-images.githubusercontent.com/8073510/79713976-fc573100-8301-11ea-858e-85d3571d73e8.png">

The actual reason is a bug in cosmos-sdk which we fixed in Maxonrow. [here](https://github.com/maxonrow/cosmos-sdk/commit/140408d9ed5209c1226cb434203b0a770d83fe64)

We need to make it backward compatible for sdk-users

**Comment by jeansoonsik** [comment]
@b00f Thanks for the updates. Please make sure that it is backward compatible in the coming release.

**Comment by b00f** [comment]
@yenkhoon any update?

**Comment by b00f** [comment]
@yenkhoon As we discussed you need to just replace string. Do you have any difficulties?
