### ISSUE TITLE
Event List for NFT

### ISSUE THREAD

**Issue by b00f** [maxonrow/maxonrow-go#107]
We should update [EVENTS.md](https://github.com/maxonrow/maxonrow-go/blob/develop/EVENTS.md) For NFT (non-fungible-toke).  

Also we need to describe parameters for KYC, Fee and Bank modules, like FT events.

**Comment by githubckgoh1439** [comment]
Mostafa,

Will follow up this later.

**Comment by githubckgoh1439** [comment]
Hi, Mostafa

Any guideline on how to update base on this ?  eg, value of Event Hashing
ID

TQ.

**Comment by b00f** [comment]
@githubckgoh1439 You had documented these before. For example look [here](https://maxonrow-docs.readthedocs.io/en/latest/modules/nonfungible/msgtype/CreateNonFungibleToken.html). Check the event section. You can find the signatures. I think you can check the hash from the code or ask @yenkhoon

**Comment by githubckgoh1439** [comment]
Hi, Mostafa

TQ on the comments. Will follow up this and check with YK later.

**Comment by githubckgoh1439** [comment]
Mostafa and YK 

I still working on the Fabric 2.0 chaincode and yet to update this as per request.

May be YK can help on this update later. TQ YK.
