### ISSUE TITLE
Query Token Information

### ISSUE THREAD

**Issue by carlo-chung** [maxonrow/maxonrow-go#156]
Add new RPC function(s) to query information of a `specific` FT or NFT symbol. Information returned: Token properties, metadata, fee settings.

**Comment by b00f** [comment]
Currently we have two methods for querying FT & NFT tokens.  Look [here](https://github.com/maxonrow/maxonrow-go/blob/d597230ea1ea3278f5fcaa3f0a277d2f8944f18d/app/app.go#L308)
Currently these methods list all FT and NFT tokens. We need to add new parameter to query only requested tokens.
