### ISSUE TITLE
Enhancement make Max Length of Endorser list configurable

### ISSUE THREAD

**Issue by yenkhoon** [maxonrow/maxonrow-go#179]
- Endorser list should be configurable.

**Comment by b00f** [comment]
@jeansoonsik and @carlo-chung 

Imagine, a person send a spam transaction with thousands of endorser's address, We can easily revoke his KYC. We have mechanism to prevent the spamming in our blockchain. This extra check is just make our NFT more sophisticated and hard to maintain.

**Comment by carlo-chung** [comment]
We set maximum length for many things in our blockchain, e.g. name, properties, metadata, etc, for the same reason, an endorser list needs to have a maximum length too.
Under a governed blockchain, even though we have a revoke KYC function, that doesn't imply we don't control the limits.
Furthermore, this is a good feature for some business use cases.

**Comment by yenkhoon** [comment]
what is the recommended maximum number of endorser list can be set to? or we don't limit it at all?
