### ISSUE TITLE
RPC endpoint to see the authorized account for FT/NFT

### ISSUE THREAD

**Issue by b00f** [maxonrow/maxonrow-go#192]
We need to add a new RPC endpoint  or modify current RPC (`/ft_info` and `/nft_info`) to show the authorized accounts for FT and NFT modules. This should works similar to  kyc_info end point.

Check [here](https://alloys-rpc.maxonrow.com/debug/kyc_info?) to see kyc_info for alloy chain (test net).

**Comment by nagarajmanjunath** [comment]
completed !
