### ISSUE TITLE
there's no client-command query feeCollector?

### ISSUE THREAD

**Issue by PandaTea** [maxonrow/maxonrow-go#202]
I only found the REST interface for query feeCollector

![image](https://user-images.githubusercontent.com/29042336/97384448-b01d2700-190a-11eb-85cd-1d6529d3d7ed.png)

It would be more convenient to have a cli-command that query feeCollector

**Comment by b00f** [comment]
@yenkhoon Do we have cli command for query fee info?

**Comment by PandaTea** [comment]
I've added a [cli-command](https://github.com/maxonrow/maxonrow-go/pull/203#issue-513570238) to make it easier to query feeCollector.

**Comment by b00f** [comment]
Awesome! thanks for adding new CLI command for querying feeCollector. 
There are some errors in Travis but I believe it's because of new version of go.

**Comment by PandaTea** [comment]
thank u for the king wordsQvQ, you r great team. Good luck with your work.
