### ISSUE TITLE
MultiSig tests

### ISSUE THREAD

**Issue by b00f** [maxonrow/maxonrow-go#34]
These test cases should be done for multi-sig:
- Owner is nil
- Threshold is 0, negative value, greater than Threshold
- Length of signer is zero (no signer)

**Comment by githubckgoh1439** [comment]
Goh have questions on the NFTs part, mostafa and YK please comments as below  :

Example of Happy-path flow : 
-- Step-1 : Create-token 
-- Step-2 : Approve-token  
-- Step-3 : Mint-item
-- Step-4 : Burn-item
-- Step-5 : Transfer-ownership of token

**Question : Do we also need this process : endorsement-item ?

Q1. 
For Create-token, Mint-item, Burn-item,
-- Signer & Token-owner are the same account-user : eg. multiSig-Account-1 ?

Q2.
For the Approve-token after Create-token, 
-- Signer will be the multiSig-Account-1 ?
-- Do we need this Endorser List ?

Q3.
For the Transfer-ownership of token,
-- Signer & Token-owner are the same account-user : eg. multiSig-Account-1 ?
-- New Token-owner : multiSig-Account-2 ?

**Comment by b00f** [comment]
> Do we also need this process : endorsement-item ?

Endorsement is optional. 

> For Create-token, Mint-item, Burn-item,

Create-token & mint-item should be token owner (multisig-acc-1). But burn-item is item owner (alice). @yenkhoon right?

> For the Transfer-ownership of token,
Yes, Current token owner (multi-sig-acc1) sign token-ownership-transfer message. New owner (ex. multi-sig-acc-2) should confirm.

**Comment by yenkhoon** [comment]
@b00f is correct. endorsement is optional. any wallet is kyced in the blockchain, they can do endorsement or if the token were created with endorsement list then only those in the list can endorse.

**Comment by githubckgoh1439** [comment]
Hi, Mostafa & YK

TQ for the update.

This with LATEST example of Happy-path flows as I understood : 
-- Step-1 : Create-token 
-- Step-2 : Approve-token  (without input for endorserList)
-- Step-3 : Mint-item
-- Step-4 : Burn-item
-- Step-5 : Transfer-ownership of token
-- Step-6 : Accept-token-ownership

1.
I will ignore this endorsement-item process, as will depend the multiSign-acc whom already whitelisted to sign this Internal-tx for Mint-item. 
Meanwhile, I will ignore the input for the endorserList during the Approve-token.

2.   
I will use Current token owner (eg. multi-sig-acc-1) to sign this Internal-tx for Transfer-ownership of token. After that, will use New token owner (eg. multi-sig-acc-2) to sign this Internal-tx for Accept-token-ownership.


Any issues will update both of u later. TQ

**Comment by b00f** [comment]
Sounds good. thanks. Let me know if you face  any difficulties

**Comment by githubckgoh1439** [comment]
Ya, Mostafa. 

Will update if any issue later.  Sorry, just finish studied base on above and come out the idea.

TQ both.
