### ISSUE TITLE
Broadcasting internal transaction when rpc is disabled

### ISSUE THREAD

**Issue by b00f** [maxonrow/maxonrow-go#39]
Currently multi-sig broadcast internal transaction via rpc. 
What happens if RPC is disabled?
We need to find a way to not use RPC for broadcasting transaction.

**Comment by yenkhoon** [comment]
our rpc cant be disabled anyway. Some portion of the ante.go require it to retrieve chain-id and block number.

**Comment by yenkhoon** [comment]
thi is the line 213 in ante.go:

res, err := rpc.Block(nil, &num)

**Comment by yenkhoon** [comment]
can we close this issue?

**Comment by b00f** [comment]
Did we test it when the rpc is closed?

**Comment by yenkhoon** [comment]
closing this issue.
