### ISSUE TITLE
Update debug/fee rpc endpoint

### ISSUE THREAD

**Issue by b00f** [maxonrow/maxonrow-go#43]
currently `debug/fee` rpc endpoint shows the list of fees and parameters.
We need to add more information about fee assignment:
- Token+Acion => Fee_name
- Account => Fee_name
- Msg => Fee_name

**Comment by nagarajmanjunath** [comment]
Fixed the rpc endpoint !!

**Comment by yenkhoon** [comment]
@nagarajmanjunath reference the pull request!
