### ISSUE TITLE
Request for localnet merge into master  branch

### ISSUE THREAD

**Issue by jeansoonsik** [maxonrow/maxonrow-go#84]
We need to have the localnet guideline and docker image pointer into the master branch.

**Comment by b00f** [comment]
Our goal is to update master branch (merging it with develop branch) whenever we upgrade the main-net. Currently main-net version is 1.0.0, but our develop branch is versioned 1.2.0. Till we upgrade main net you can use this link to use docker image:
https://github.com/maxonrow/maxonrow-go/tree/develop/docker
