### ISSUE TITLE
Derivation of sdk and blockchain is the same but multisig didnt get created

### ISSUE THREAD

**Issue by yenkhoon** [maxonrow/maxonrow-go#92]
<img width="1440" alt="Screenshot 2020-03-25 at 18 28 30" src="https://user-images.githubusercontent.com/1153905/77527288-dab38700-6ec6-11ea-967c-1069c5cd4589.png">

<img width="1440" alt="Screenshot 2020-03-25 at 18 31 48" src="https://user-images.githubusercontent.com/1153905/77527358-eef78400-6ec6-11ea-83a0-054c100da66c.png">

refer to the above two screen shot, the derivation of group address is same in sdk and core.

However after created I query the blockchain it seems that the multisig isnt created.

<img width="1440" alt="Screenshot 2020-03-25 at 18 33 23" src="https://user-images.githubusercontent.com/1153905/77527480-282ff400-6ec7-11ea-94a7-f695651f3198.png">

**Comment by yenkhoon** [comment]
1st picture notice the group address which is mxw1x4ck6pfn58347wm4ej90xn3p2pcfd2d96w2ay6 calculated from sdk

2nd picture is calculated from blockchain.

3rd the multisig isnt created.

**Comment by yenkhoon** [comment]
@b00f @jeansoonsik

**Comment by b00f** [comment]
It resolved here: https://github.com/yenkhoon/mxw-sdk-js/pull/1

SDK should consider to increase the nonce for calculating wallet address. Refer to the above PR for more information.
