### ISSUE TITLE
verifying multisig transaction uses signature slice and pubkey slice.

### ISSUE THREAD

**Issue by yenkhoon** [maxonrow/maxonrow-go#93]
```
for _, stdSig := range stdSigs {
		// signerAcc is groupAccount
		signBytes := GetSignBytes(ctx, tx, signerAcc)
		matched := false
		for i, pubKey := range pubKeys {

			if pubKey == nil {
				continue
			}
			abc, _ := sdkTypes.AccAddressFromHex(pubKey.Address().String())
			fmt.Println(abc.String())
			if pubKey.VerifyBytes(signBytes, stdSig.Signature) {
				signedBy, err := sdkTypes.AccAddressFromHex(pubKey.Address().String())
				if err != nil {
					return nil, err
				}
				if !signerAcc.IsSigner(signedBy) {
					return nil, sdkTypes.ErrUnauthorized("Unauthorized signer: %v")
				}

				if !kycKeeper.IsWhitelisted(ctx, signedBy) {
					return nil, sdkTypes.ErrInternal(fmt.Sprintf("Transaction signer is not whitelisted: %v", signer))
				}

				//
				pubKeys[i] = nil

				matched = true
				break
			} else {
				fmt.Println(string(stdSig.Signature))
			}
		}

		if !matched {
			return nil, sdkTypes.ErrUnauthorized("signature verification failed; verify correct account sequence and chain-id" + string(signBytes))
		}
	}
```

We cant certain the pubkey and signature are matching, slice is random the sequence is random. Once the signbytes failed to get verify, we will get signature verification error.

**Comment by yenkhoon** [comment]
@b00f @jeansoonsik

**Comment by b00f** [comment]
Can you explain ore how the signature verification can fail?

For any signature we iterate all the  public keys to match them with the signature.
Sequence should not be random here: In multi_sig sequence is same as tx_id which is not random and it is sequential. 
In non multi_sig there is always one public key and one signature.

**Comment by githubckgoh1439** [comment]
YK & Mostafa,

I get this same error message while I testing for multiSig-NFTs
by running this '/maxonrow-go/tests/multisigNFTs_test.go'.

You can refer this test-case :
1. 'Create MultiSig Tx for NFTs [Approve-token] - Happy path -  commit.'

Also under the issue been prompted out before this :
-- https://github.com/maxonrow/maxonrow-go/pull/89

**Comment by b00f** [comment]
> I get this same error message while I testing for multiSig-NFTs

Which message?

**Comment by githubckgoh1439** [comment]
Hi, Mostafa

I run this test-case under file of 'tests/multisigNFTs_test.go' : 
[
Create MultiSig Tx for NFTs [Approve-token] - Happy path - commit.'
]

and get this error : 
[
return nil, sdkTypes.ErrUnauthorized("signature verification failed; verify correct account sequence and chain-id" + string(signBytes))
]

Please help to check, since last Wednesday.

**Comment by b00f** [comment]
@githubckgoh1439 This is because it has wrong tx_id. is should be 3, not 0.
